import type { NodeKind } from "@/lib/types";

export const KIND_META: Record<NodeKind, { label: string; icon: string; accent: string }> = {
  rectangle: { label: "Block", icon: "▢", accent: "oklch(0.55 0.02 60)" },
  circle: { label: "Node", icon: "○", accent: "oklch(0.55 0.02 60)" },
  diamond: { label: "Decision", icon: "◇", accent: "oklch(0.6 0.15 60)" },
  database: { label: "Database", icon: "⛁", accent: "oklch(0.55 0.15 250)" },
  api: { label: "API", icon: "{}", accent: "oklch(0.6 0.18 145)" },
  frontend: { label: "Frontend", icon: "❐", accent: "oklch(0.6 0.18 30)" },
  backend: { label: "Backend", icon: "▤", accent: "oklch(0.5 0.15 280)" },
  website: { label: "Website", icon: "◐", accent: "oklch(0.6 0.15 210)" },
  discord: { label: "Discord", icon: "✦", accent: "oklch(0.55 0.18 270)" },
  queue: { label: "Queue", icon: "≡", accent: "oklch(0.65 0.15 80)" },
  cache: { label: "Cache", icon: "⏃", accent: "oklch(0.62 0.16 50)" },
  webhook: { label: "Webhook", icon: "↯", accent: "oklch(0.6 0.18 320)" },
  auth: { label: "Auth", icon: "⚿", accent: "oklch(0.55 0.16 25)" },
  ai: { label: "AI", icon: "✸", accent: "oklch(0.6 0.2 300)" },
  storage: { label: "Storage", icon: "▣", accent: "oklch(0.55 0.12 200)" },
  custom: { label: "Custom", icon: "✱", accent: "oklch(0.5 0.04 60)" },
  note: { label: "Note", icon: "✎", accent: "oklch(0.7 0.14 90)" },
  todo: { label: "To-do", icon: "☑", accent: "oklch(0.6 0.16 145)" },
  image: { label: "Image", icon: "▦", accent: "oklch(0.6 0.12 210)" },
  link: { label: "Link", icon: "⌘", accent: "oklch(0.6 0.18 240)" },
  code: { label: "Code", icon: "</>", accent: "oklch(0.55 0.14 160)" },
  markdown: { label: "Markdown", icon: "M↓", accent: "oklch(0.55 0.04 60)" },
  terminal: { label: "Terminal", icon: ">_", accent: "oklch(0.4 0.02 60)" },
  cdn: { label: "CDN", icon: "☁", accent: "oklch(0.65 0.14 220)" },
  loadbalancer: { label: "Load Balancer", icon: "⇄", accent: "oklch(0.6 0.16 195)" },
  analytics: { label: "Analytics", icon: "▥", accent: "oklch(0.62 0.18 100)" },
  email: { label: "Email", icon: "✉", accent: "oklch(0.6 0.14 35)" },
  payment: { label: "Payment", icon: "$", accent: "oklch(0.6 0.16 135)" },
  mobile: { label: "Mobile", icon: "▯", accent: "oklch(0.6 0.16 285)" },
  iot: { label: "IoT", icon: "⛬", accent: "oklch(0.6 0.14 60)" },
  mlmodel: { label: "ML Model", icon: "∂", accent: "oklch(0.6 0.2 310)" },
  "vector-db": { label: "Vector DB", icon: "⌗", accent: "oklch(0.55 0.16 265)" },
  cron: { label: "Cron", icon: "◷", accent: "oklch(0.62 0.12 70)" },
  secret: { label: "Secret", icon: "🔑", accent: "oklch(0.55 0.16 20)" },
  monitoring: { label: "Monitoring", icon: "◉", accent: "oklch(0.6 0.18 15)" },
  kanban: { label: "Kanban", icon: "▤", accent: "oklch(0.6 0.12 180)" },
};

export const ALL_KINDS: NodeKind[] = Object.keys(KIND_META) as NodeKind[];